default_config:
google:
  client_id: !secret google_id
  client_secret: !secret google_secret
ios:

homekit: !include homekit.yaml

light: !include light.yaml

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

http:
octoprint:
  host: octopi.local
  api_key: !secret octokey
  bed: true

camera:
  - platform: generic
    name: 3d_printer
    still_image_url: http://octopi.local/webcam/?action=snapshot
    stream_source: http://octopi.local/webcam/?action=stream

media_player:
  - platform: philips_android_tv
    name: living_room TV
    host: !secret ph_ip
    mac: !secret ph_mac
    username: !secret ph_user
    password: !secret ph_pass

sensor: !include_dir_merge_list sensors/
device_tracker: !include_dir_list device_tracker/
group: !include_dir_merge_named groups
switch: !include_dir_merge_list switch/
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts
homeassistant:
  customize: !include customize.yaml
circadian_lighting:
  min_colortemp: 2700
  max_colortemp: 6500
  interval: 30
  transition: 3

alarm_control_panel:
  - platform: manual
    name: Alarmanlage
    code: !secret alarm_code
    arming_time: 30
    delay_time: 30
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

binary_sensor: !include_dir_merge_list binary_sensors/
person:
  - name: Fabi
    id: fabi
    device_trackers:
      - device_tracker.presence_fabi
  - name: Mate
    id: mate
    device_trackers:
      - device_tracker.presence_mate
  - name: Partner
    id: partner
    device_trackers:
      - device_tracker.presence_partner
tts:
  - platform: google_translate
    base_url: !secret local

input_datetime:
  last_door:
    name: last door opening
    has_date: true
    has_time: true
  last_cleaning:
    name: last cleaning
    has_date: true
    has_time: true
input_select: !include_dir_merge_named input_select
input_boolean: !include_dir_named input_boolean
input_number:
  bin:
    name: vaccum_bin_counter
    min: 0
    max: 10
    step: 1
    mode: box
input_text:
  hall_text:
    name: Hall_Text
    initial: Restarting...
  tmp:
    name: tmp text
    initial: ""
  awtrix_notify:
    name: Awtrix Notify
    initial: Hello, World!
    icon: mdi:form-textarea

utility_meter:
  living_room_energy:
    source: sensor.living_room_plug_energy
    cycle: monthly
  workspace_energy:
    source: sensor.workspace_plug_energy
    cycle: monthly
