
- platform: wake_on_lan
  mac: !secret pc_mac
  name: Spielerechner
  host: 192.168.0.104
  turn_off:
    service: script.shutdown

- platform: circadian_lighting
  lights_rgb:
    - light.schlafzimmer_links
    - light.schlafzimmer_rechts
  name: Schlafzimmer
  disable_brightness_adjust: False

- platform: circadian_lighting
  lights_rgb:
    - light.schlafzimmer_led
  name: Kartenstrip
  disable_brightness_adjust: False

- platform: circadian_lighting
  lights_rgb:
    - light.wintergarten_links
    - light.wintergarten_rechts
  name: Wintergarten
  disable_brightness_adjust: True

- platform: circadian_lighting
  lights_rgb:
    - light.aussenlampe
  name: Aussenlampe
  disable_brightness_adjust: True

- platform: circadian_lighting
  lights_ct:
    - light.lagerlampe
  name: Lagerlampe
  disable_brightness_adjust: True

- platform: circadian_lighting
  lights_ct:
    - light.kuechenlampe
  name: Kueche
  disable_brightness_adjust: True

- platform: circadian_lighting
  lights_ct:
    - light.esstisch
  name: Esstisch
  disable_brightness_adjust: True

  ## Switch to use in HomeKit
- platform: template
  switches:
    manual_staubi:
      value_template: "off"
      turn_on:
        service: vacuum.start
        data:
          entity_id: vacuum.rockrobo
      turn_off:
        service: vacuum.return_to_base
        data:
          entity_id: vacuum.rockrobo
