##
## If an resident arrives home, he will be greeted
##


- alias: 'Presence - Paul greeting'
  trigger:
     - platform: state
       entity_id:
            - input_boolean.paul_home
       to: 'on'

  action:
    - service: script.speech_engine
      data_template:
        personarriving: >
          {%- macro greeting_sentence() -%}
          {{ [
          "Na Paul was geht so?",
          "Willkommen Zuhause Paul",
          "Endlich bist du wieder Zuhause Paul",
          "Piece Out Paul",
          "Doppel Piece Paul",
          "Juhu, Paul ist wieder Zuhause",
          "Na wer ist denn da wieder Zuhause? Ich habe dich schon vermisst",
          "Hallo Paul"
          ] | random }}
          {%- endmacro -%}
          {{greeting_sentence()}}
        call_responsibilities: 0
        call_random: 1
        call_no_announcement: 1
        call_garage_check: 0
        call_window_check: 0
    - service: script.led_notification
      data_template:
        message: "Hey Paul!"
        
- alias: 'Presence - Fabi greeting'
  trigger:
     - platform: state
       entity_id:
            - input_boolean.fabian_home
       to: 'on'
  action:
    - service: script.speech_engine
      data_template:
        personarriving: >
          {%- macro greeting_sentence() -%}
          {{ [
          "Na Fabian was geht so?",
          "Willkommen Zuhause Fabian",
          "Endlich bist du wieder Zuhause Fabian",
          "Piece Out Fabian",
          "Doppel Piece Fabian",
          "Juhu, Fabi ist wieder Zuhause",
          "Na wer ist denn da wieder Zuhause? Ich habe dich schon vermisst",
          "Hallo Fabi"
          ] | random }}
          {%- endmacro -%}
          {{greeting_sentence()}}
        call_responsibilities: 0
        call_random: 1
        call_no_announcement: 1
        call_garage_check: 0
        call_window_check: 0
    - service: script.led_notification
      data_template:
        message: "Hey Fabi!"
        
- alias: 'Presence - Fabi greeting'
  trigger:
     - platform: state
       entity_id:
            - input_boolean.lelo_home
       to: 'on'

  action:
    - service: script.speech_engine
      data_template:
        personarriving: >
          {%- macro greeting_sentence() -%}
          {{ [
          "Na Leelo was geht so?",
          "Willkommen Zuhause, Leelo",
          "Endlich bist du wieder Zuhause, Leelo",
          "Piece Out, Leelo",
          "Doppel Piece, Leelo",
          "Juhu, Leelo ist wieder Zuhause",
          "Na wer ist denn da wieder Zuhause? Ich habe dich schon vermisst",
          "Hallo Leelo"
          ] | random }}
          {%- endmacro -%}
          {{greeting_sentence()}}
        call_responsibilities: 0
        call_random: 1
        call_no_announcement: 1
        call_garage_check: 0
        call_window_check: 0
    - service: script.led_notification
      data_template:
          message: "Hey Lelo!"

      