##
## If an resident arrives at home, he will be greeted
##

- alias: "Presence - Mate greeting"
  trigger:
    - platform: state
      entity_id:
        - input_boolean.mate_home
      to: "on"

  action:
    - service: script.speech_engine
      data_template:
        personarriving: !include /config/templates/secret/greetings/mate.yaml
        call_responsibilities: 0
        call_random: 1
        call_no_announcement: 1
        call_garage_check: 0
        call_window_check: 0
    - service: script.led_update
    - service: script.led_notification
      data_template:
        message: !secret hey_mate

- alias: "Presence - Fabi greeting"
  trigger:
    - platform: state
      entity_id:
        - input_boolean.fabi_home
      to: "on"
  action:
    - service: script.speech_engine
      data_template:
        personarriving: !include /config/templates/secret/greetings/fabi.yaml
        call_responsibilities: 0
        call_random: 1
        call_no_announcement: 1
        call_garage_check: 0
        call_window_check: 0
    - service: script.led_update
    - service: script.led_notification
      data_template:
        message: "Hey Fabi!"

- alias: "Presence - Partner greeting"
  trigger:
    - platform: state
      entity_id:
        - input_boolean.partner_home
      to: "on"

  action:
    - service: script.speech_engine
      data_template:
        personarriving: !include /config/templates/secret/greetings/partner.yaml
        call_responsibilities: 0
        call_random: 1
        call_no_announcement: 1
        call_garage_check: 0
        call_window_check: 0
    - service: script.led_update
    - service: script.led_notification
      data_template:
        message: !secret hey_partner
