##
## These automations start the arrive- and depart scans for "monitor"
## TODO: Source
##

- alias: "Presence - Start Departscan"
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.vestibule_front_door_contact
    to: "off"
    for:
      seconds: 5
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.home_count
          state: "0"
  action:
    - service: script.scan_bt_depart

- alias: "Presence - Start Arrivescan"
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.vestibule_front_door_contact
    to: "on"

  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.home_count
          state: "1"
  action:
    - service: script.scan_bt_arrive
