##
## Covers all automations that happen when no one is at home anymore
##

- alias: "Presence - No one is home"
  trigger:
    - platform: state
      entity_id:
        - input_boolean.mate_home
        - input_boolean.partner_home
        - input_boolean.fabi_home
      from: "on"
      to: "off"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.fabi_home
        state: "off"
      - condition: state
        entity_id: input_boolean.mate_home
        state: "off"
      - condition: state
        entity_id: input_boolean.partner_home
        state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.home_occupied
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.alarmanlage
        code: !secret alarm_code

- alias: "Presence - Turn off all lights"
  trigger:
    - platform: state
      entity_id:
        - input_boolean.home_occupied
      to: "off"
  action:
    - service: switch.turn_off
      entity_id:
        - switch.steckdose2
        - switch.workspace_fairy_lights
        - switch.stairway_light
    - service: light.turn_off
      entity_id:
        - light.bogenstrip
        - light.workspace_strip
        - light.kitchen_lamp
        - light.storage_room_lamp
        - light.bedroom_lamp_left
        - light.bedroom_lamp_right
        - light.living_room_left
        - light.living_room_right
        - light.dining_table
        - light.dining_table_ambilight
        - light.hall_strip
        - light.living_room_strip
    - service: light.turn_on
      data:
        entity_id: light.740aa7b1_77fedd44
        brightness: 1
    - service: input_select.select_option
      data:
        entity_id: input_select.led_sign_mode
        option: Disabled
