##
## Covers all automations corresponding the storage room button.
##

## Force Returns vacuum robot to his base
- alias: "Storage Room - button double - start vacuum"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.storage_room_button_click
    to: "double"
  condition:
    condition: state
    entity_id: vacuum.rockrobo
    state: docked
  action:
    - service: vacuum.start
      entity_id: vacuum.rockrobo

## Force vacuum robot to clean
- alias: "Storage Room - button double - return vacuum"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.storage_room_button_click
    to: "double"
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: vacuum.rockrobo
      state: docked
  action:
    - service: vacuum.return_to_base
      entity_id: vacuum.rockrobo
    - delay: 2
    - service: vacuum.return_to_base
      entity_id: vacuum.rockrobo

- alias: Storage Room - button single
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.storage_room_button_click
    to: "single"
  action:
    - service: light.toggle
      data:
        entity_id:
          - light.storage_room_lamp
        brightness: 250
        color_temp: 320

- alias: Storage Room - button triple
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.storage_room_button_click
    to: "triple"
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.disco
