##
## Covers all Automation regarding the LED Strip in the Bedroom
##

## Led Strip should only be on, when the bedside lamps are on
- alias: "Bedroom - turn on LED strip"
  trigger:
    platform: state
    entity_id:
      - light.bedroom_lamp_left
      - light.bedroom_lamp_right
    to: "on"
  action:
    service: light.turn_on
    entity_id: light.bedroom_strip

## Led Strip should only be on, when the bedside lamps are on
- alias: "Bedroom - turn on LED strip"
  trigger:
    - platform: state
      entity_id: light.bedroom_lamp_left
      to: "off"
    - platform: state
      entity_id: light.bedroom_lamp_right
      to: "off"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.bedroom_lamp_left
        state: "off"
      - condition: state
        entity_id: light.bedroom_lamp_right
        state: "off"
  action:
    service: light.turn_off
    entity_id: light.bedroom_strip
