##
## Covers all Automation concerning the bedside lampe
## Note that the bedside lampe
##

- alias: Bedroom - Turn on Bedside Lamp Lelo
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.bedroom_button_click
    to: "single"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.fabi_in_bed
        state: "True"
      - condition: state
        entity_id: sensor.lelo_in_bed
        state: "False"
  action:
    - service: light.toggle
      data:
        entity_id:
          - light.bedroom_lamp_left
        brightness: 1

- alias: Bedroom - Turn on Bedside Lamp Fabi
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.bedroom_button_click
    to: "single"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.fabi_in_bed
        state: "False"
      - condition: state
        entity_id: sensor.lelo_in_bed
        state: "True"
  action:
    - service: light.toggle
      data:
        entity_id:
          - light.bedroom_lamp_right
        brightness: 1

## if nobody is in Bed, toggle the lamps with full brightness
- alias: "Bedroom - Single Press, lights on"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.bedroom_button_click
    to: "single"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.fabi_in_bed
        state: "False"
      - condition: state
        entity_id: sensor.lelo_in_bed
        state: "False"
      - condition: state
        entity_id: light.bedroom_lamp_right
        state: "off"
  action:
    - service: script.bedroom_bright

## if nobody is in bed, turn both lights off
- alias: "Bedroom - Single Press, lights off"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.bedroom_button_click
    to: "single"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.fabi_in_bed
        state: "False"
      - condition: state
        entity_id: sensor.lelo_in_bed
        state: "False"
      - condition: state
        entity_id: light.bedroom_lamp_right
        state: "on"
  action:
    - service: light.turn_off
      entity_id:
        - light.bedroom_lamp_right
        - light.bedroom_lamp_left
