##
## covers all automations concerning the bedside lamps
##

- alias: Bedroom - Turn on Bedside Lamp Partner
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.bedroom_door_action
    to: "open"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.fabi_in_bed
        state: "True"
      - condition: state
        entity_id: sensor.partner_in_bed
        state: "False"
  action:
    - service: light.toggle
      data:
        entity_id:
          - light.bedroom_lamp_left
        brightness: 1

- alias: Bedroom - Turn on Bedside Lamp Fabi
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.bedroom_door_action
    to: "open"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.fabi_in_bed
        state: "False"
      - condition: state
        entity_id: sensor.partner_in_bed
        state: "True"
  action:
    - service: light.toggle
      data:
        entity_id:
          - light.bedroom_lamp_right
        brightness: 1

## If nobody is in bed, toggle the lamps to full brightness.
- alias: "Bedroom - Single Press, lights on"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.bedroom_door_action
    to: "open"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.fabi_in_bed
        state: "False"
      - condition: state
        entity_id: sensor.partner_in_bed
        state: "False"
      - condition: state
        entity_id: light.bedroom_lamp_right
        state: "off"
  action:
    - service: script.bedroom_bright

## If nobody is in bed, turn both lights off.
- alias: "Bedroom - Single Press, lights off"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.bedroom_door_action
    to: "open"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.fabi_in_bed
        state: "False"
      - condition: state
        entity_id: sensor.partner_in_bed
        state: "False"
      - condition: state
        entity_id: light.bedroom_lamp_right
        state: "on"
  action:
    - service: light.turn_off
      entity_id:
        - light.bedroom_lamp_right
        - light.bedroom_lamp_left

## cover down
- alias: "Bedroom - Cover Down"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.bedroom_door_action
    to: "close"
  condition:
    - condition: numeric_state
      entity_id: cover.bedroom_left
      value_template: "{{ state.attributes.position }}"
      above: 99
  action:
    - service: cover.close_cover
      entity_id:
        - cover.bedroom_left
        - cover.bedroom_right

## cover up
- alias: "Bedroom - Cover Up"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.bedroom_door_action
    to: "close"
  condition:
    - condition: numeric_state
      entity_id: cover.bedroom_left
      value_template: "{{ state.attributes.position }}"
      below: 100
  action:
    - service: cover.open_cover
      entity_id:
        - cover.bedroom_left
        - cover.bedroom_right
