##
## Covers all automations based on the weight of the residents.
##

- alias: Bedroom - partner get up
  initial_state: False
  trigger:
    platform: state
    entity_id: sensor.partner_in_bed
    from: "True"
    to: "False"
    for:
      seconds: 3
  condition:
    condition: time
    after: "22:00:00"
    before: "6:00:00"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.bedroom_lamp_left
        brightness: 1

- alias: Bedroom - partner lays down
  initial_state: False
  trigger:
    platform: state
    entity_id: sensor.partner_in_bed
    from: "False"
    to: "True"
    for:
      seconds: 3
  condition:
    condition: time
    after: "22:00:00"
    before: "6:00:00"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.bedroom_lamp_left

- alias: Bedroom - fabi get up
  initial_state: False
  trigger:
    platform: state
    entity_id: sensor.fabi_in_bed
    from: "True"
    to: "False"
    for:
      seconds: 3
  condition:
    condition: time
    after: "00:00:00"
    before: "6:00:00"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.bedroom_lamp_right
        brightness: 1

- alias: Bedroom - fabi lays down
  initial_state: False
  trigger:
    platform: state
    entity_id: sensor.fabi_in_bed
    from: "False"
    to: "True"
    for:
      seconds: 3
  condition:
    condition: time
    after: "00:00:00"
    before: "6:00:00"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.bedroom_lamp_right

## Turn off the get up / lay down automations.
- alias: "Bedroom - night is over"
  initial_state: True
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: automation.turn_off
      entity_id:
        - automation.bedroom_fabi_lays_down
        - automation.bedroom_fabi_get_up
        - automation.bedroom_partner_lays_down
        - automation.bedroom_partner_get_up

## The get up / lay down automations are only turned on, if someone lays
## longer then 15 min in bed.
- alias: "Bedroom - night begins for partner"
  initial_state: True
  trigger:
    platform: state
    entity_id:
      - sensor.partner_in_bed
    to: "True"
    for:
      minutes: 15
  condition:
    condition: time
    after: "22:00:00"
    before: "6:00:00"
  action:
    - service: automation.turn_on
      entity_id:
        - automation.bedroom_partner_lays_down
        - automation.bedroom_partner_get_up

- alias: "Bedroom - night begins for partner"
  initial_state: True
  trigger:
    platform: state
    entity_id:
      - sensor.fabi_in_bed
    to: "True"
    for:
      minutes: 15
  condition:
    condition: time
    after: "22:00:00"
    before: "6:00:00"
  action:
    - service: automation.turn_on
      entity_id:
        - automation.bedroom_fabi_lays_down
        - automation.bedroom_fabi_get_up
