## After n times of cleaning, the vacuum robot drives to the bin and waits for
## his cleaning. After doing that this button does command him back home.
- alias: Kitchen - Vacuum return to base after clearing bin
  trigger:
    platform: state
    entity_id: sensor.kitchen_button_click
    to: "close"
  condition:
    - condition: state
      entity_id: input_boolean.vacuum_clear_bin
      state: "on"

  action:
    - service: vacuum.return_to_base
      entity_id: vacuum.rockrobo
    - service: input_boolean.turn_off
      entity_id: input_boolean.vacuum_clear_bin
    - service: script.clear_led_hard
    - service: script.led_notification
      data_template:
        message: "Danke!"
    - service: input_number.set_value
      data:
        entity_id: input_number.bin
        value: 0

## After 10 clearing, the vacuum robot drives to the bin and
## waits for cleaning
- alias: Vacuum - Empty Vacuum Robot
  trigger:
    - platform: state
      entity_id: input_number.bin
  condition:
    - condition: numeric_state
      entity_id: "input_number.bin"
      above: 9
  action:
    ## if the new driving location is set too fast after docking,
    ## it will be ignored
    - delay: 10
    - service: script.move_vacuum_to_bin
    - service: input_boolean.turn_on
      entity_id: input_boolean.vacuum_clear_bin
    - service: script.awtrix_advanced_notify
      data_template:
        message: "Bitte Staubi leeren!"
        icon: 1053
    - service: script.led_hard
      data_template:
        message: "Bitte Staubi leeren!"

## After Vacuum Robot finished, increment the bin number. It is used to to
## determine when he needs to be cleared
- alias: Vacuum - Cleaning finished
  trigger:
    - platform: state
      entity_id: vacuum.rockrobo
      from: "cleaning"
      to: "docked"
    - platform: state
      entity_id: vacuum.rockrobo
      from: "returning"
      to: "docked"

  action:
    - service: input_number.increment
      entity_id: input_number.bin

- alias: Kitchen - Clean kitchen
  trigger:
    platform: state
    entity_id: sensor.kitchen_button_click
    to: "close"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacuum_clear_bin
        state: "off"
      - condition: state
        entity_id: vacuum.rockrobo
        state: "idle"

  action:
    - service: script.clean_kitchen
      entity_id: vacuum.rockrobo
