## short notification that cleaning was finished.
- alias: Vacuum - rockrobo goes home
  id: Vacuum - rockrobo_goes_home
  trigger:
    platform: state
    entity_id: vacuum.rockrobo
    to: "returning"
  action:
    - service: script.awtrix_advanced_notify
      data_template:
        message: "Saeuberung beendet!"
        icon: 1043
    - service: script.led_notification
      data_template:
        message: "Saeuberung beendet!"
