- alias: LED_Sign - Disable
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.led_sign_mode
    to: Disabled
  action:
    - service: input_text.set_value
      data:
        entity_id: input_text.hall_text
        value: ""
