- alias: Disco - Turn on
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.disco
    to: "on"

  action:
    - service: light.turn_off
      entity_id: light.dining_table
    - service: switch.turn_off
      entity_id:
        - switch.circadian_lighting_bedroom
        - switch.circadian_lighting_storage_room_lamp
        - switch.circadian_lighting_kitchen
    - service: light.turn_on
      data_template:
        entity_id:
          - light.workspace_strip
          - light.living_room_strip
          - light.bedroom_strip
          - light.hall_strip
          - light.kitchen_strip
        brightness: 255
        effect: colorloop

    - service: light.turn_on
      data_template:
        entity_id:
          - light.wintergarten_light_wall
          - light.vestibule_lamp
          - light.bedroom_lamp_left
          - light.bedroom_lamp_right
          - light.storage_room_lamp
          - light.dining_table_ambilight
          - light.workspace_window_light
        brightness: 255
        effect: "Random Loop"

- alias: Disco - Turn off
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.disco
    to: "off"

  action:
    - service: script.random_color
    - service: circadian_lighting.values_update
    - service: wled.effect
      data_template:
        entity_id: light.bedroom_strip
        effect: 0
    - service: light.turn_off
      entity_id: light.bedroom_strip
    - service: light.turn_on
      entity_id:
        - light.vestibule_lamp
        - light.storage_room_lamp
      data_template:
        brightness: 250
        color_temp: 320
    - service: switch.turn_on
      entity_id:
        - switch.circadian_lighting_bedroom
        - switch.circadian_lighting_storage_room_lamp
        - switch.circadian_lighting_kitchen
