- alias: "Doorbell - someone there"
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_contact
    from: "on"
    to: "off"
  action:
    - service: notify.mobile_app_iphone_von_fabian_during
      data:
        message: "Jemand ist an der Tuer!"
        title: "Klingel"
    - service: notify.mobile_app_partner_phone
      data:
        message: "Jemand ist an der Tuer!"
        title: "Klingel"
    - service: media_player.volume_set
      entity_id:
        - media_player.workspace
        - media_player.kitchen
        - media_player.living_room
        - media_player.bedroom
      data:
        volume_level: 0.5

    - service: media_player.play_media
      entity_id:
        - media_player.workspace
        - media_player.kitchen
        - media_player.living_room
        - media_player.bedroom
      data:
        media_content_id: http://192.168.0.5:8123/local/da_dong.mp3
        media_content_type: "music"
