- platform: philips_ambilight+hue
  name: living_room_ambihue
  host: !secret ph_ip
  username: !secret ph_user
  password: !secret ph_pass
  id: 2131230778 # ambilight_hue_off node id. Default is 2131230774, but some newer TVs use 2131230778 instead.
  scan_interval: 5
