##
## Switches to add a roundabout way for unsupported integrations
##

- platform: template
  switches:
    manual_staubi:
      value_template: "off"
      turn_on:
        service: vacuum.start
        data:
          entity_id: vacuum.rockrobo
      turn_off:
        service: vacuum.return_to_base
        data:
          entity_id: vacuum.rockrobo
