## turn on Living Room Light if the TV(AVR) is on
- alias: Living Room - Lights on evening
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.evening_mode
    to: "on"
  condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: media_player.denon_avr
        state: "on"
      - condition: state
        entity_id: input_boolean.ambilight
        state: "off"
  action:
    - service: circadian_lighting.values_update
      entity_id:
        - light.living_room_left
        - light.living_room_right
    - service: light.turn_on
      data:
        entity_id:
          - light.living_room_right
          - light.living_room_left

- alias: Living Room - enable Ambilight+Hue
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.ambilight
    to: "on"
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_ambihue
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_living_room

- alias: Living Room - disable Ambilight+Hue
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.ambilight
    to: "off"
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_ambihue