## turn on Living Room Light if the TV(AVR) is on
- alias: Living Room - Lights on evening
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.evening_mode
    to: "on"
  condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: media_player.denon_avr
        state: "on"
      - condition: state
        entity_id: input_boolean.ambilight
        state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.living_room_right
          - light.living_room_left