- alias: 'Info - led 10 - AVR in Living Room is on'
  initial_state: on
  trigger:
  - platform: state
    entity_id: media_player.denon_avr_x1500h
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.debug_led10
      data: 
        color_name: red

- alias: "Info - led 10 - AVR in Living Room is off"
  initial_state: on
  trigger:
  - platform: state
    entity_id: media_player.denon_avr_x1500h
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.debug_led10