- alias: "Info - led 5 - Fabi is home"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_fabi
      to: "home"
  action:
    - service: light.turn_on
      entity_id: light.debug_led5
      data:
        color_name: green

- alias: "Info - led 5 - Fabi is not home"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_fabi
      to: "not_home"
  action:
    - service: light.turn_off
      entity_id: light.debug_led5

- alias: "Info - led 5 - Fabi is unknown"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_fabi
      to: "unknown"
  action:
    - service: light.turn_on
      entity_id: light.debug_led5
      data:
        color_name: red
