- alias: 'Info - led 7 - Some lights are on'
  initial_state: on
  trigger:
  - platform: state
    entity_id: group.all_lights
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.debug_led7
      data: 
        color_name: red

- alias: "Info - led 7 - No lights are on"
  initial_state: on
  trigger:
  - platform: state
    entity_id: group.all_lights
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.debug_led7