- alias: 'Info - switch 1 - clean kitchen'
  initial_state: off
  trigger:
  - platform: state
    entity_id: binary_sensor.ad
    to: 'on'
  - platform: state
    entity_id: binary_sensor.ad
    to: 'off'
  action:
    - service: script.clean_kitchen

