- alias: "Info - led 1 - garbage collection tomorrow"
  initial_state: on
  trigger:
    - platform: state
      entity_id: sensor.garbage_collection
      to: "True"
  action:
    - service: light.turn_on
      entity_id: light.debug_led1
      data:
        color_name: blue

- alias: "Info - led 1 - no garbage collection tomorrow"
  initial_state: on
  trigger:
    - platform: state
      entity_id: sensor.garbage_collection
      to: "False"
  action:
    - service: light.turn_off
      entity_id: light.debug_led1
