- alias: 'Info - led 11 - Evening Mode is on'
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.evening_mode
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.debug_led11
      data: 
        color_name: red

- alias: "Info - led 11 - Evening Mode is off"
  initial_state: on
  trigger:
  - platform: state
    entity_id: input_boolean.evening_mode
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.debug_led11