- alias: 'Info - led 2 - vacuum robot is cleaning'
  initial_state: on
  trigger:
  - platform: state
    entity_id: vacuum.rockrobo
    to: "cleaning"
  action:
    - service: light.turn_on
      entity_id: light.debug_led2
      data: 
        color_name: green

- alias: 'Info - led 2 - vacuum robot is not cleaning'
  initial_state: on
  trigger:
  - platform: state
    entity_id: vacuum.rockrobo
    to: "docked"
  action:
    - service: light.turn_off
      entity_id: light.debug_led2