- alias: 'Info - led 3 - bedroom lights are on'
  initial_state: on
  trigger:
  - platform: state
    entity_id: group.bedroom_lights
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.debug_led3
      data: 
        color_name: red

- alias: "Info - led 3 - bedroom lights are off"
  initial_state: on
  trigger:
  - platform: state
    entity_id: group.bedroom_lights
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.debug_led3