- alias: "Info - led 4 - mate is home"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_mate
      to: "home"
  action:
    - service: light.turn_on
      entity_id: light.debug_led4
      data:
        color_name: green

- alias: "Info - led 4 - mate is not home"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_mate
      to: "not_home"
  action:
    - service: light.turn_off
      entity_id: light.debug_led4

- alias: "Info - led 4 - mate is unknown"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_mate
      to: "unknown"
  action:
    - service: light.turn_on
      entity_id: light.debug_led4
      data:
        color_name: red
