- alias: "Info - led 6 - partner is home"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_partner
      to: "home"
  action:
    - service: light.turn_on
      entity_id: light.debug_led6
      data:
        color_name: green

- alias: "Info - led 6 - partner is not home"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_partner
      to: "not_home"
  action:
    - service: light.turn_off
      entity_id: light.debug_led6

- alias: "Info - led 6 - partner is unknown"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_partner
      to: "unknown"
  action:
    - service: light.turn_on
      entity_id: light.debug_led6
      data:
        color_name: red
