- alias: "Info - led 6 - Lelo is home"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_lelo
      to: "home"
  action:
    - service: light.turn_on
      entity_id: light.debug_led6
      data:
        color_name: green

- alias: "Info - led 6 - Lelo is not home"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_lelo
      to: "not_home"
  action:
    - service: light.turn_off
      entity_id: light.debug_led6

- alias: "Info - led 6 - Lelo is unknown"
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.presence_lelo
      to: "unknown"
  action:
    - service: light.turn_on
      entity_id: light.debug_led6
      data:
        color_name: red
