##
## The acustical feedback can be enabled and disabled
##

- alias: "Enable acustical feedback"
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.feedback
      to: "off"
  action:
    - service: script.speech_engine
      data_template:
        random: >
          {%- macro greeting_sentence() -%}
          {{ [
          "Ihr werdet mich vermissen!",
          "Akustisches Benachrichtigungssystem wird deaktiviert. Einen schönen Tag noch!"
          ] | random }}
          {%- endmacro -%}
          {{greeting_sentence()}}
        call_responsibilities: 0
        call_no_announcement: 1
        call_garage_check: 0
        call_random: 0
        call_window_check: 0
        media_player: media_player.kitchen
    - delay: 1
    - service: input_boolean.turn_on
      entity_id: input_boolean.muted

- alias: "Disable acustical feedback"
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.feedback
      to: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.muted
    - delay: 1
    - service: script.speech_engine
      data_template:
        random: >
          {%- macro greeting_sentence() -%}
          {{ [
          "Da bin ich wieder! Mal schauen was der Tag so bringt...",
          "Akustisches Benachrichtigungssystem wird gestartet"
          ] | random }}
          {%- endmacro -%}
          {{greeting_sentence()}}
        call_responsibilities: 0
        call_random: 1
        call_no_announcement: 1
        call_garage_check: 0
        call_window_check: 0
        media_player: media_player.kitchen
