- platform: dwd_weather_warnings
  region_name: !secret location_city

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: load_1m
    - type: processor_use

- platform: moon

- platform: darksky
  api_key: !secret darksky
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_intensity_max
    - temperature
    - wind_speed
    - cloud_cover
    - humidity
    - minutely_summary
    - uv_index
    - sunrise_time
    - sunset_time

- platform: time_date
  display_options:
    - "time"