- alias: "Outside - motion light on"
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.outdoor_motion_occupancy
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.evening_mode
      state: "on"
  action:
    - service: light.turn_on
      entity_id: light.outdoor_lamp
    - service: script.awtrix_advanced_notify
      data_template:
        message: "Haustür"
        icon: 709

- alias: "Outside - motion light off"
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.outdoor_motion_occupancy
    from: "on"
    to: "off"
  action:
    - service: light.turn_off
      entity_id: light.outdoor_lamp
