##
## Covers all automations regarding the garbage collection.
##

## The calendar.mulltonne shows whether the garbage collection is coming.
##  - acoustic feedback
##  - visual feedback
- alias: "Garbage Collection - Tomorrow"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.garbage_collection
    to: "True"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.mulltonne
    - service: script.led_hard
      data_template:
        message: "{{ state_attr('calendar.muelltonne', 'message') }}"

## To force the residents to move the trash they get an notification every hour.
- alias: "Garbage Collection - Notification"
  initial_state: True
  trigger:
    platform: time_pattern
    minutes: "/59"
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.partner_home
            state: "on"
          - condition: state
            entity_id: input_boolean.fabi_home
            state: "on"
          - condition: state
            entity_id: input_boolean.mate_home
            state: "on"
      - condition: state
        entity_id: input_boolean.mulltonne
        state: "on"
  action:
    - service: script.led_hard
      data_template:
        message: "{{ state_attr('calendar.muelltonne', 'message') }}"

- alias: "Garbage Collection - Completed"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.workspace_double_click
    to: "both_double"
  condition:
    - condition: state
      entity_id: input_boolean.mulltonne
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.mulltonne
    - service: script.clear_led_hard
