##
## Covers all automations concerning the main entrance door
##

- alias: Vestibule - Notify fabi when door open too long
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.vestibule_front_door_contact
    to: "on"
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: input_boolean.fabi_home
    state: "on"
  action:
    - service: notify.mobile_app_fabi_phone
      data:
        message: "Die Haustür steht länger als 5 Minuten offen"
        title: "Warnung"

- alias: Vestibule - Notify partner when door open too long
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.vestibule_front_door_contact
    to: "on"
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: input_boolean.partner_home
    state: "on"
  action:
    - service: notify.mobile_app_pic_lx9
      data:
        message: "Die Haustür steht länger als 5 Minuten offen"
        title: "Warnung"

- alias: Vestibule - Notify acustically when door open too long
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.vestibule_front_door_contact
    to: "on"
    for:
      minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.partner_home
        state: "on"
      - condition: state
        entity_id: input_boolean.fabi_home
        state: "on"
      - condition: state
        entity_id: input_boolean.mate_home
        state: "on"
  action:
    #- service: script.speech_engine
    #  data_template:
    #    personarriving: >
    #      "Die Haustür ist seit 5 Minuten offen. Kann sie bitte jemand zumachen?"
    #    call_responsibilities: 0
    #    call_random: 1
    #    call_no_announcement: 1
    #    call_garage_check: 0
    #    call_window_check: 0
    - service: input_boolean.turn_on
      entity_id: input_boolean.vestibule_front_door_open_5
    - service: script.led_hard
      data_template:
        message: "Haustuer schliessen!"
        symbol: "E"

- alias: Vestibule - Door closes after too long
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.vestibule_front_door_contact
    to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.vestibule_front_door_open_5
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.vestibule_front_door_open_5
    - service: script.clear_led_hard
