##
## All necessary steps before and after a restart
##

- alias: Miscellaneous - HA Start
  trigger:
    - event: start
      platform: homeassistant
  action:
    - service: switch.turn_on
      entity_id:
        - switch.circadian_lighting_dining_table
        - switch.circadian_lighting_kitchen
        - switch.circadian_lighting_bedroom
        - switch.circadian_lighting_kartenstrip
    ## trigger the information loop
    - service: script.led_update

    ## restart the "monitor" service
    - service: mqtt.publish
      data_template:
        topic: presence/scan/restart

- alias: Miscellaneous - HA Restarting/Stop
  trigger:
    - event: shutdown
      platform: homeassistant
  action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.hall_text
        value: "Restarting..."
