##
## All Events which corresponds evening_mode
##

- alias: Evening - Ambient Light when someone home
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.evening_mode
    to: "on"
  condition:
    condition: state
    entity_id: input_boolean.home_occupied
    state: "on"
  action:
    - service: script.random_color
    - service: script.led_notification
      data_template:
        message: "Sonnenuntergang"
    - service: script.speech_engine
      data_template:
        call_responsibilities: 0
        call_no_announcement: 1
        call_dark_outside: 1
        call_random: 1
        call_garage_check: 0
        call_window_check: 0
