##
## Covers all automations around the tablet on ground_floor.
## powered by Fully Kiosk Browser
##

## turn it back on, when someone comes to ground floor

- alias: "Workspace - Turn on fire when someone ground"
  initial_state: True
  trigger:
    platform: state
    entity_id:
      - light.living_room_left
      - light.living_room_right
      - light.kitchen_lamp
      - light.schreibtischlampe
      - light.storage_room_lamp
      - light.workspace_window_light
      - light.workspace_strip
      - light.living_room_strip
      - light.dining_table
      - light.dining_table_ambilight
      - light.vestibule_lamp
      - light.storage_room_whiteboard
    to: "on"
  condition:
    - condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: "02:00:00"
        - condition: sun
          before: sunrise
  action:
    - service: light.turn_on
      data:
        entity_id: light.3524c986_aa76e656
        brightness: 150
    - service: light.turn_on
      entity_id:
        - light.awtrix_lights
    - service: input_select.select_option
      data:
        entity_id: input_select.led_sign_mode
        option: Default

## Turns on tablet on sunrise.

- alias: "Workspace - Tablet on on sunrise"
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: light.turn_on
      data:
        entity_id: light.3524c986_aa76e656
        brightness: 150
    - service: light.turn_on
      entity_id:
        - light.awtrix_lights
    - service: input_select.select_option
      data:
        entity_id: input_select.led_sign_mode
        option: Default
