##
## covers all automations corresponding the kitchen button
##

- alias: "Kitchen - Light on/off"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.kitchen_door_action
    to: "open"
  action:
    - service: light.toggle
      entity_id: light.kitchen_lamp
    - service: light.toggle
      entity_id: light.kitchen_strip
