- alias: "Kitchen - No Motion"
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    from: "on"
    to: "off"
    for:
      minutes: 10
  action:
    - service: light.turn_off
      entity_id: light.kitchen_lights

- alias: "Kitchen - Motion"
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    from: "off"
    to: "on"
  condition:
    condition: state
    entity_id: input_boolean.evening_mode
    state: "on"
  action:
    - service: light.turn_on
      entity_id: light.kitchen_lights
